### ISSUE TITLE
kernel size of U-F#Net

### ISSUE THREAD

**Issue by yhy258** [pdearena/pdearena#31]
Hello, Thanks for providing the code.

When initializing Upsample and Downsample, you used a convolutional layer with a kernel size of 3 in this code, does this not violate the Discretization Invariance property of the Neural Operator?

**Comment by brandstetter-johannes** [comment]
Hi @yhy258, you are right. If you want to have invariance properties you should use kernel size = 1. However, for these examples resolutions are the same, so it does not matter. In general, UNets are not a-priori discretization invariant in contrast to FNOs. There are ways to achieve discretization invariance for UNets though, an example is provided here: https://arxiv.org/abs/2302.01178
