### ISSUE TITLE
How to perform model inference?

### ISSUE THREAD

**Issue by RC-circuit** [pdearena/pdearena#35]
I trained the pderefiner model with the 1D KS dataset on my system and stored the weights. When I attempt to load the weights from the ckpt file and perform inference, it throws errors saying positional argument 'pdeconfig' is missing even after providing all the necessary arguments. If anyone has made an inference with the model, can you please help me in resolving the issue? Thanks

**Comment by rejuvyesh** [comment]
Can you share the exact commands and errors that you run into?
